In [1]:
import os
import pandas as pd
import numpy as np
import torch
from zero_shot_filter import ZeroShot, ZeroShotOutput

In [2]:
torch.__version__

'2.2.0'

In [3]:
os.listdir("/home/pranavgoel/trans-fer-entropy/obtaining_news_collections/data/")

['newyork_article_texts_and_info_dedup.csv',
 'nytimes_foxnews_article_texts_and_info.csv',
 'nytimes_foxnews_article_texts_and_info_dedup.csv',
 'florida_article_texts_and_info_dedup.csv',
 'california_article_texts_and_info.csv',
 'mediacloud_us_national_july_dec_2023.csv',
 'mediacloud_illinois.csv',
 'mediacloud_ohio.csv',
 'texas_article_texts_and_info.csv',
 'illinois_article_texts_and_info_dedup.csv',
 'illinois_article_texts_and_info.csv',
 'texas_article_texts_and_info_dedup.csv',
 'california_article_texts_and_info_dedup.csv',
 'mediacloud_newyork.csv',
 'ohio_article_texts_and_info.csv',
 'mediacloud_florida.csv',
 'mediacloud_us_national_jan_jun_2023.csv',
 'prior_data_apr_jun_2023',
 'mediacloud_california.csv',
 'ohio_article_texts_and_info_dedup.csv',
 'florida_article_texts_and_info.csv',
 'mediacloud_texas.csv',
 'newyork_article_texts_and_info.csv',
 '.ipynb_checkpoints']

In [4]:
data = pd.read_csv("/home/pranavgoel/trans-fer-entropy/obtaining_news_collections/data/nytimes_foxnews_article_texts_and_info_dedup.csv")

In [5]:
test_data = data.iloc[0:100]

In [12]:
test_data

media_name publish_date  \
0   foxnews.com   2023-06-16   
1   foxnews.com   2023-06-25   
2   foxnews.com   2023-04-06   
3   foxnews.com   2023-06-16   
4   foxnews.com   2023-06-12   
..          ...          ...   
95  foxnews.com   2023-03-23   
96  foxnews.com   2023-04-10   
97  foxnews.com   2023-03-21   
98  foxnews.com   2023-03-30   
99  foxnews.com   2023-05-31   

                                                title  \
0   Blockbuster film 'Spider-Man: Across the Spide...   
1   Bud Light controversy dismissed by country art...   
2   Country music's Travis Tritt drops all Anheuse...   
3   Garth Brooks' Bud Light controversy: Country s...   
4   Garth Brooks controversy: Bud Light drama foll...   
..                                                ...   
95  Black mother comes out against lowering academ...   
96  Black mother files complaint against teacher f...   
97  Black parent ‘insulted’ by district's proposal...   
98  Boston Children's Hospital director calls for ...   
99  Boston Children's Hospital says it doesn't per...   

                                                  url  \
0   https://www.foxnews.com/entertainment/blockbus...   
1   https://www.foxnews.com/entertainment/bud-ligh...   
2   https://www.foxnews.com/entertainment/country-...   
3   https://www.foxnews.com/entertainment/garth-br...   
4   https://www.foxnews.com/entertainment/garth-br...   
..                                                ...   
95  https://www.foxnews.com/media/black-mother-com...   
96  https://www.foxnews.com/media/black-mother-fil...   
97  https://www.foxnews.com/media/black-parent-ins...   
98  https://www.foxnews.com/media/boston-childrens...   
99  https://www.foxnews.com/media/boston-childrens...   

                                             subtitle  \
0   The film "Spider-Man: Across the Spider-Verse"...   
1   Country star Tyler Farr shared his thoughts on...   
2   Country singer-songwriter Travis Tritt became ...   
3   Garth Brooks remained defiant that he will ser...   
4   Garth Brooks is a country icon, but he has had...   
..                                                ...   
95  Sylvia Nelson, a mother of two, felt insulted ...   
96  A Long Island high school is caught up in cont...   
97  Sylvia Nelson, a mother of two, told a local n...   
98  Boston Children's Hospital's director of gende...   
99  Boston Children's Hospital senior clinicians d...   

                                                 text  sent_count  
0   "Spider-Man: Across the Spider-Verse" debuted ...          25  
1   The world of country music is currently mired ...          69  
2   Country singer-songwriter Travis Tritt announc...          25  
3   Garth Brooks is continuing to take a stand aga...          26  
4   Garth Brooks is a beloved country icon and per...          86  
..                                                ...         ...  
95  A Cincinnati mother of two told Fox News Digit...          30  
96  A Long Island high school is caught up in cont...          29  
97  A parent spoke out in opposition to a school d...          32  
98  Boston Children's Hospital co-director at its ...          28  
99  FOX NEWS INVESTIGATES – Almost one year ago, B...          66  

[100 rows x 7 columns]

In [6]:
test_filter = ZeroShot()

In [13]:
test_preds = test_filter.batch_classify(datapath=None, labels=['transgender', 'not transgender'], data=test_data, col_name='text')

Classifying Batch: 100%|████████████████████████| 13/13 [00:31<00:00,  2.39s/it]


In [14]:
test_preds.data

((0,
  '"Spider-Man: Across the Spider-Verse" debuted in theaters across the United States in the beginning of June. It tripled the domestic opening weekend revenue of its prequel.\n\nOver a dozen Muslim-majority countries pulled the blockbuster film from theaters without explanation.\n\nMany people believe the film was banned because of the inclusion of a transgender poster in the background of one frame during the movie.\n\nThe new blockbuster movie "Spider-Man: Across the Spider-Verse" was abruptly removed from cinema listings in more than a dozen Muslim-majority countries without explanation, apparently over the inclusion of a blink-and-you-miss-it transgender poster in the background of one frame.\n\nEmpire Entertainment, the Middle East distributor for the computer-animated Sony Pictures film, did not respond to multiple requests for comment.\n\nNo explicit bans of the film were announced, but there were indications that it will not reach screens.\n\nFor example, there is no expe

# SCRIPT WRITING

In [8]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer

In [9]:
model = AutoModelForSequenceClassification.from_pretrained('facebook/bart-large-mnli')

In [10]:
type(model)

transformers.models.bart.modeling_bart.BartForSequenceClassification

In [11]:
tokenizer = AutoTokenizer.from_pretrained('facebook/bart-large-mnli')

In [14]:
tokenizer.encode('Potatoes are the best freaking food ever', 'oranges', return_tensors='pt', truncation='only_first')

tensor([[    0, 35516, 31198,    32,     5,   275, 33432,   689,   655,     2,
             2,   368, 33094,     2]])

In [16]:
type(tokenizer.encode('Orange are ok', 'oranges', return_tensors='pt', truncation='only_first'))

torch.Tensor

In [22]:
logits=model(tokenizer.encode('Orange are ok', 'oranges', return_tensors='pt', truncation='only_first'))[0]

In [23]:
entail_contradiction_logits = logits[:,[0,2]]

In [24]:
entail_contradiction_logits

tensor([[-2.2049,  2.6060]], grad_fn=<IndexBackward0>)

In [25]:
logits

tensor([[-2.2049, -0.5254,  2.6060]], grad_fn=<AddmmBackward0>)

In [27]:
probs = entail_contradiction_logits.softmax(dim=1)

In [30]:
probs[:,1].item()

0.9919251799583435